coverage:
  range: "60...100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: 60%
        threshold: 0.1%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 0.1%
        informational: true
    changes:
      default:
        target: 60%
        threshold: 0.1%
        informational: true
